server:
  port: 8083

spring:

  application:
    name: movie-service


  config:
    import: optional:configserver:http://localhost:8888/
# H2

  h2:
    console:
#      enabled: true
      path: /h2-console

# Datasource

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


# JPA/Hibernate

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true






